name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    container: wirecardtecdoc/texlive:cairo

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: out/
        key: ${{ runner.os }}-docs-diagrams-${{ hashFiles('src/*.tex') }}
        restore-keys: |
          ${{ runner.os }}-docs-diagrams-

    - name: Build PDFs and SVGs
      run: make -j 8

    - name: Move artifacts
      run: |
        mkdir -p artifacts
        mv out/*.pdf out/*.svg out/*.png artifacts/
        cp scripts/names.txt artifacts/

    - uses: actions/upload-artifact@v1
      with:
        name: diagrams
        path: artifacts/

